#!/bin/sh
# autopkgtest check: Build and run a program against ign-cmake, to verify that the
# cmake modules are installed
# (C) 2012 Jose Luis Rivero
# Author: Jose Luis Rivero <jrivero@osrfoundation.org>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
mkdir -p $WORKDIR/doc $WORKDIR/src $WORKDIR/include $WORKDIR/test
touch $WORKDIR/doc/CMakeLists.txt $WORKDIR/src/CMakeLists.txt $WORKDIR/include/CMakeLists.txt $WORKDIR/test/CMakeLists.txt
cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.5)

project(test VERSION 1.0.0)

#============================================================================
# Find ignition-cmake3
#============================================================================
# If you get an error at this line, you need to install ignition-cmake3
find_package(ignition-cmake3 REQUIRED)

#============================================================================
# Set up the project
#============================================================================
ign_configure_project()

#============================================================================
# Configure the build
#============================================================================
ign_configure_build(QUIT_IF_BUILD_ERRORS)
EOF

cmake .
echo "configure: OK"
